# Generated by Django 3.2.5 on 2021-07-27 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('houseId', models.AutoField(primary_key=True, serialize=False)),
                ('houseName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('requestId', models.AutoField(primary_key=True, serialize=False)),
                ('studentName', models.CharField(max_length=100)),
                ('studentSurname', models.CharField(max_length=100)),
                ('identification', models.IntegerField(max_length=10)),
                ('age', models.IntegerField(max_length=3)),
                ('idSchool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiSolicitud.school')),
            ],
        ),
    ]
