# Generated by Django 3.2.5 on 2021-07-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiSolicitud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='identification',
            field=models.CharField(max_length=100),
        ),
    ]
